### ISSUE TITLE
Internal server error while generating internal server error page

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#404]
This line in the exception handling view (https://github.com/harvard-lil/h2o/blob/master/app/views/exception_handler/exceptions/show.html.erb#L20) is trying to make links in the footer to these pages (https://github.com/harvard-lil/h2o/blob/master/lib/locales/en/errors.yml#L16) and `link_to` cannot find the route for the faq page.

```
App 7123 stderr: Error during failsafe response: undefined method `faq_path' for #<#<Class:0x00557ceb3bd540>:0x007fee59d03078>
App 7123 stderr:   /usr/local/share/h2o/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.0.rc1/lib/action_dispatch/routing/polymorphic_routes.rb:249:in `handle_string_call'
App 7123 stderr:   /usr/local/share/h2o/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.0.rc1/lib/action_view/routing_url_for.rb:111:in `url_for'
App 7123 stderr:   /usr/local/share/h2o/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.0.rc1/lib/action_view/helpers/url_helper.rb:195:in `link_to'
App 7123 stderr:   /usr/local/share/h2o/app/views/exception_handler/exceptions/show.html.erb:21:in `block in _app_views_exception_handler_exceptions_show_html_erb__3778444161650013112_46997514710340'
App 7123 stderr:   /usr/local/share/h2o/app/views/exception_handler/exceptions/show.html.erb:20:in `each_pair'
App 7123 stderr:   /usr/local/share/h2o/app/views/exception_handler/exceptions/show.html.erb
```

If I recall, Casey thinks this is probably because the FAQ is a static page generated by a gem? Could just remove the link from the footer of the error page for a quick fix.

**Comment by rebeccacremona** [comment]
Just checked: this is still 500s. I'll see if I can fix.
